import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Photo from "./_Components/photo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased w-[1440px] h-[1024px] m-auto flex gap-[24px] justify-center items-center`}
    >
      {children}
      <Photo />
    </div>
  );
}
