import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_Components/Header";
import { UserProvider } from "./_context/sigupcontext";
import { Toaster } from "@/components/ui/sonner";
import CategoryProvider from "./_context/category";
import FoodProvider from "./_context/foods";
import CloudnaryProvider from "./_context/cloudnaryimage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <CloudnaryProvider>
          <UserProvider>
            <FoodProvider>
              <CategoryProvider>{children}</CategoryProvider>
            </FoodProvider>
          </UserProvider>
        </CloudnaryProvider>

        <Toaster />
      </body>
    </html>
  );
}
